class UiPosition:
    UPLOAD_FILE_BUTTON_X = 10
    UPLOAD_FILE_BUTTON_Y = 10

    UPLOAD_FILE_LABEL_X = 10
    UPLOAD_FILE_LABEL_Y = 50

    PLAY_FILE_BUTTON_X = 80
    PLAY_FILE_BUTTON_Y = 260

    PREDICT_FILE_BUTTON_X = 300
    PREDICT_FILE_BUTTON_Y = 260

    OUTPUT_LABEL_X = 300
    OUTPUT_LABEL_Y = 80

    CONTEXT_LABEL_X = 250
    CONTEXT_LABEL_Y = 50

    URL_LABEL_X = 10
    URL_LABEL_Y = 100

    URL_TEXT_X = 10
    URL_TEXT_Y = 120

    DOWNLOAD_BUTTON_X = 10
    DOWNLOAD_BUTTON_Y = 150

    DOWNLOAD_PROGRESS_X = 10
    DOWNLOAD_PROGRESS_Y = 180
